### ISSUE TITLE
module 'pcraster' has no attribute 'numpy'

### ISSUE THREAD

**Issue by ghost** [WilcoTerink/SPHY#1]
Hi, I'm using Pcraster 4.3. Dose the Pcraster version should be downgraded?

**Comment by john-hydro** [comment]
Done, due to the version

**Comment by FANSCRAZY** [comment]
> 
Pcraster 4.3 can be use?

**Comment by ghost** [comment]
Hi Wilco, 

Thanks , I have figured it out. Yes, Pcraster 4.3 can be used. 



***@***.***
 
From: FANSCRAZY
Date: 2022-05-18 09:28
To: WilcoTerink/SPHY
CC: john-hydro; State change
Subject: Re: [WilcoTerink/SPHY] module 'pcraster' has no attribute 'numpy' (Issue #1)
Pcraster 4.3 can be use?

**Comment by FANSCRAZY** [comment]
> Hi Wilco, Thanks , I have figured it out. Yes, Pcraster 4.3 can be used. ***@***.*** From: FANSCRAZY Date: 2022-05-18 09:28 To: WilcoTerink/SPHY CC: john-hydro; State change Subject: Re: [WilcoTerink/SPHY] module 'pcraster' has no attribute 'numpy' (Issue #1) Pcraster 4.3 can be use? — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you modified the open/close state.Message ID: ***@***.***>

thanks for your reply
