### ISSUE TITLE
ROUTED FLUXES save in the main directory

### ISSUE THREAD

**Issue by jingheng-huang** [WilcoTerink/SPHY#2]
Hi, It seems there are two issues in the model.
1. I have given an output diirectory in the global file. All output files have been saved to the right directory, expect for  the Time-series output, whihch have been saved to the main folder where the sphy.py is. 
2. The stations maps seem only can have one station?  Because the second column of the output TSS file is nan. ( I have checked the location of the points, it seems right) 
Could you take a look? thanks.

**Comment by WilcoTerink** [comment]
1) Yes, this is how PCRaster is set-up: it will always save the .tss files in the directory where the code is run from.
2) I do not know how you map looks like. It is important that the station.map is a nominal map where the stations are number from one until the amount of stations, so if you for example have four stations, then they should be numbers as 1, 2, 3, 4. Another reason why there could be NaNs is that a kc value is missing for a certain type of lands class.

**Comment by jingheng-huang** [comment]
> 

Thanks a lot! It is really helpful. If I want to do many experiments at once, do you have any suggestions for keeping the output TSS file from being overwritten?

**Comment by WilcoTerink** [comment]
Hi,

Yes, just run the model in a loop, where at the end of each model execution you rename and copy the tss files to a folder of interest.
