### ISSUE TITLE
QGIS crash dumped when I add stations.map

### ISSUE THREAD

**Issue by Amalsarfraz** [WilcoTerink/SPHY#3]
Hi, 

I am working on the HinduKush-Karakoram-Himalaya database and whenever I add the stations.map the SPHY model plugin in QGIS crashes. 
![crash dumped qgis](https://user-images.githubusercontent.com/86368249/195095037-9ce5e54b-85a7-4441-a5a1-4c03b341d66d.PNG)
I have tried reinstalling the software and rebooting the system, but it is not working.

**Comment by WilcoTerink** [comment]
Is the map a nominal pcraster map with stations numbered from 1 to the number of stations?

**Comment by Amalsarfraz** [comment]
yes, that is it the one I add.

**Comment by WilcoTerink** [comment]
Can you send me this map so I can have a look at it?

**Comment by Amalsarfraz** [comment]
I am unable to send here. Should I email it you ?

**Comment by WilcoTerink** [comment]
ok
