### ISSUE TITLE
Snowmelt Infiltration

### ISSUE THREAD

**Issue by ghost** [WilcoTerink/SPHY#4]
Hi Terink, 

Is that true the model doesn't condiser the Snowmelt Infiltration process?  All the infiltration comes from the rainfall?

**Comment by WilcoTerink** [comment]
Hi,Yes that’s correct. Snowmelt leaves the grid cell as runoff when it exceeds the maximum holding capacity of the snow pack.Hope that answers your question.Cheers WilcoOn 13 Oct 2023, at 21:48, john-hydro ***@***.***> wrote:﻿
Hi Terink,
Is that true the model doesn't condiser the Snowmelt Infiltration process?  All the infiltration comes from the rainfall?
